[package]
name = "derive-rustc-index"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
ra-ap-rustc_index = "0.86"
syn = { version = "2", features = ["full"] }
