[package]
name = "aecium"
version = "0.0.0"
license = "MIT"
description = "Experimental alternative Rust frontend."
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
ra_ap_parser = "0.0.248"
